export const list = [
    {
        type: 'third_party',
        color: 'text-darkRed',
        cookies: [
            '__cf_bm',
            '__utma',
            '__utmb',
            '__utmc',
            '__utmv',
            '__utmz',
            '_fbp',
            '_ga',
            '_ga_TM005KXVR9',
            '_gid',
            '_sp_id.b2e4',
            '_sp_ses.b2e4',
            '_uetsid',
            '_uetvid',
            'ga_sessions',
            'mf_b44341da-ab3a-4407-bc7e-95f1282969bd',
            'moe_uuid',
            '__utmt',
            'defaultImg',
            'sw_regexitintentla',
            '_dd_s',
            'joe-chnlcustid',
            'spd-custhash',
            '_gat',
            '_gat_UA-1319529-26',
            '_gat_gaVirtualPage',
            'ga_custom_vars',
            '_sp_id.6fbe',
            'sd',
            'sw_ei_pe_DSH524990',
            'sw_ei_pe_matri0607',
        ]
    },
    {
        type: 'not_needed',
        color: 'text-lightRed',
        cookies: [
            'browser_key',
            'mid_token',
            'misc2',
            'webp_support',
            'mplan',
            'entpt',
            'entpt-session',
            'is_ptp',
            'sessionLogin',
            'revampView',
            'abCampaign',
            'canary_bucket',
            'counter',
            'flotbotParam',
            'rippleUpgradeShown',
            'ab_impression_email_matches',
            'has_requested_notifications',
            'photo_docking',
            'ust',
            'loginattempt',
            'misc',
            'layer_banners',
            'ad_profile_income_grp',
            'ads',
            'dns',
            'memberblkyn',
            'psc',
            'VOC',
            'fmpage',
            'multiple_photos_experiement',
            'etrk',
            'no_photo_docking',
        ]
    },
    {
        type: 'needed',
        color: 'text-darkGreen',
        cookies: [
            'i2c',
            'mid',
            '_alxm',
            'ltabc',
            'abc',
            'memberAccType',
            '_mat',
            'admagnet',
            'abtrk',
            'premium_support_ab',
            'gptrk',
            'abclogin',
            'hi_er',
            'loginMigrationExpv2',
            'isExtended',
            'reg_logger'
        ]
    },
    {
        type: 'set_on_homepage',
        color: 'text-lightGreen',
        cookies: [
            'affiliate',
            'first_ptnr',
            'webp',
            'sessionptnr',
            'reg_ust',
            'aff_url_param',
        ]
    }
]